# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: client.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='client.proto',
  package='Tokens',
  syntax='proto3',
  serialized_options=b'\n\030com.keepersecurity.protoB\006Client',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0c\x63lient.proto\x12\x06Tokens\"u\n\x18\x42reachWatchUpdateRequest\x12\x42\n\x18\x62reachWatchRecordRequest\x18\x01 \x03(\x0b\x32 .Tokens.BreachWatchRecordRequest\x12\x15\n\rencryptedData\x18\x02 \x01(\x0c\"\x9c\x01\n\x18\x42reachWatchRecordRequest\x12\x11\n\trecordUid\x18\x01 \x01(\x0c\x12\x15\n\rencryptedData\x18\x02 \x01(\x0c\x12\x38\n\x13\x62reachWatchInfoType\x18\x03 \x01(\x0e\x32\x1b.Tokens.BreachWatchInfoType\x12\x1c\n\x14updateUserWhoScanned\x18\x04 \x01(\x08\"\x81\x01\n\x0f\x42reachWatchData\x12%\n\tpasswords\x18\x01 \x03(\x0b\x32\x12.Tokens.BWPassword\x12\"\n\x06\x65mails\x18\x02 \x03(\x0b\x32\x12.Tokens.BWPassword\x12#\n\x07\x64omains\x18\x03 \x03(\x0b\x32\x12.Tokens.BWPassword\"]\n\nBWPassword\x12\r\n\x05value\x18\x01 \x01(\t\x12\x10\n\x08resolved\x18\x02 \x01(\x04\x12 \n\x06status\x18\x03 \x01(\x0e\x32\x10.Tokens.BWStatus\x12\x0c\n\x04\x65uid\x18\x04 \x01(\x0c*9\n\x13\x42reachWatchInfoType\x12\n\n\x06RECORD\x10\x00\x12\x16\n\x12\x41LTERNATE_PASSWORD\x10\x01*E\n\x08\x42WStatus\x12\x08\n\x04GOOD\x10\x00\x12\x0b\n\x07\x43HANGED\x10\x01\x12\x08\n\x04WEAK\x10\x02\x12\x0c\n\x08\x42REACHED\x10\x03\x12\n\n\x06IGNORE\x10\x04\x42\"\n\x18\x63om.keepersecurity.protoB\x06\x43lientb\x06proto3'
)

_BREACHWATCHINFOTYPE = _descriptor.EnumDescriptor(
  name='BreachWatchInfoType',
  full_name='Tokens.BreachWatchInfoType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RECORD', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ALTERNATE_PASSWORD', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=529,
  serialized_end=586,
)
_sym_db.RegisterEnumDescriptor(_BREACHWATCHINFOTYPE)

BreachWatchInfoType = enum_type_wrapper.EnumTypeWrapper(_BREACHWATCHINFOTYPE)
_BWSTATUS = _descriptor.EnumDescriptor(
  name='BWStatus',
  full_name='Tokens.BWStatus',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GOOD', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CHANGED', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='WEAK', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BREACHED', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='IGNORE', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=588,
  serialized_end=657,
)
_sym_db.RegisterEnumDescriptor(_BWSTATUS)

BWStatus = enum_type_wrapper.EnumTypeWrapper(_BWSTATUS)
RECORD = 0
ALTERNATE_PASSWORD = 1
GOOD = 0
CHANGED = 1
WEAK = 2
BREACHED = 3
IGNORE = 4



_BREACHWATCHUPDATEREQUEST = _descriptor.Descriptor(
  name='BreachWatchUpdateRequest',
  full_name='Tokens.BreachWatchUpdateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='breachWatchRecordRequest', full_name='Tokens.BreachWatchUpdateRequest.breachWatchRecordRequest', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='encryptedData', full_name='Tokens.BreachWatchUpdateRequest.encryptedData', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=141,
)


_BREACHWATCHRECORDREQUEST = _descriptor.Descriptor(
  name='BreachWatchRecordRequest',
  full_name='Tokens.BreachWatchRecordRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='recordUid', full_name='Tokens.BreachWatchRecordRequest.recordUid', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='encryptedData', full_name='Tokens.BreachWatchRecordRequest.encryptedData', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='breachWatchInfoType', full_name='Tokens.BreachWatchRecordRequest.breachWatchInfoType', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='updateUserWhoScanned', full_name='Tokens.BreachWatchRecordRequest.updateUserWhoScanned', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=144,
  serialized_end=300,
)


_BREACHWATCHDATA = _descriptor.Descriptor(
  name='BreachWatchData',
  full_name='Tokens.BreachWatchData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='passwords', full_name='Tokens.BreachWatchData.passwords', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='emails', full_name='Tokens.BreachWatchData.emails', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='domains', full_name='Tokens.BreachWatchData.domains', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=303,
  serialized_end=432,
)


_BWPASSWORD = _descriptor.Descriptor(
  name='BWPassword',
  full_name='Tokens.BWPassword',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='Tokens.BWPassword.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='resolved', full_name='Tokens.BWPassword.resolved', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='Tokens.BWPassword.status', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='euid', full_name='Tokens.BWPassword.euid', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=434,
  serialized_end=527,
)

_BREACHWATCHUPDATEREQUEST.fields_by_name['breachWatchRecordRequest'].message_type = _BREACHWATCHRECORDREQUEST
_BREACHWATCHRECORDREQUEST.fields_by_name['breachWatchInfoType'].enum_type = _BREACHWATCHINFOTYPE
_BREACHWATCHDATA.fields_by_name['passwords'].message_type = _BWPASSWORD
_BREACHWATCHDATA.fields_by_name['emails'].message_type = _BWPASSWORD
_BREACHWATCHDATA.fields_by_name['domains'].message_type = _BWPASSWORD
_BWPASSWORD.fields_by_name['status'].enum_type = _BWSTATUS
DESCRIPTOR.message_types_by_name['BreachWatchUpdateRequest'] = _BREACHWATCHUPDATEREQUEST
DESCRIPTOR.message_types_by_name['BreachWatchRecordRequest'] = _BREACHWATCHRECORDREQUEST
DESCRIPTOR.message_types_by_name['BreachWatchData'] = _BREACHWATCHDATA
DESCRIPTOR.message_types_by_name['BWPassword'] = _BWPASSWORD
DESCRIPTOR.enum_types_by_name['BreachWatchInfoType'] = _BREACHWATCHINFOTYPE
DESCRIPTOR.enum_types_by_name['BWStatus'] = _BWSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BreachWatchUpdateRequest = _reflection.GeneratedProtocolMessageType('BreachWatchUpdateRequest', (_message.Message,), {
  'DESCRIPTOR' : _BREACHWATCHUPDATEREQUEST,
  '__module__' : 'client_pb2'
  # @@protoc_insertion_point(class_scope:Tokens.BreachWatchUpdateRequest)
  })
_sym_db.RegisterMessage(BreachWatchUpdateRequest)

BreachWatchRecordRequest = _reflection.GeneratedProtocolMessageType('BreachWatchRecordRequest', (_message.Message,), {
  'DESCRIPTOR' : _BREACHWATCHRECORDREQUEST,
  '__module__' : 'client_pb2'
  # @@protoc_insertion_point(class_scope:Tokens.BreachWatchRecordRequest)
  })
_sym_db.RegisterMessage(BreachWatchRecordRequest)

BreachWatchData = _reflection.GeneratedProtocolMessageType('BreachWatchData', (_message.Message,), {
  'DESCRIPTOR' : _BREACHWATCHDATA,
  '__module__' : 'client_pb2'
  # @@protoc_insertion_point(class_scope:Tokens.BreachWatchData)
  })
_sym_db.RegisterMessage(BreachWatchData)

BWPassword = _reflection.GeneratedProtocolMessageType('BWPassword', (_message.Message,), {
  'DESCRIPTOR' : _BWPASSWORD,
  '__module__' : 'client_pb2'
  # @@protoc_insertion_point(class_scope:Tokens.BWPassword)
  })
_sym_db.RegisterMessage(BWPassword)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
