# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: folder_access.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import folder_pb2 as folder__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x66older_access.proto\x12\tfolder.v3\x1a\x0c\x66older.proto\x1a\x1cgoogle/api/annotations.proto\"\xa3\x01\n\x16GetFolderAccessRequest\x12\x11\n\tfolderUid\x18\x01 \x03(\x0c\x12<\n\x11\x63ontinuationToken\x18\x02 \x01(\x0b\x32\x1c.folder.v3.ContinuationTokenH\x00\x88\x01\x01\x12\x15\n\x08pageSize\x18\x03 \x01(\x05H\x01\x88\x01\x01\x42\x14\n\x12_continuationTokenB\x0b\n\t_pageSize\"\xbd\x01\n\x17GetFolderAccessResponse\x12=\n\x13\x66olderAccessResults\x18\x01 \x03(\x0b\x32 .folder.v3.GetFolderAccessResult\x12<\n\x11\x63ontinuationToken\x18\x02 \x01(\x0b\x32\x1c.folder.v3.ContinuationTokenH\x00\x88\x01\x01\x12\x0f\n\x07hasMore\x18\x03 \x01(\x08\x42\x14\n\x12_continuationToken\")\n\x11\x43ontinuationToken\x12\x14\n\x0clastModified\x18\x01 \x01(\x03\"\x93\x01\n\x15GetFolderAccessResult\x12\x11\n\tfolderUid\x18\x01 \x01(\x0c\x12+\n\taccessors\x18\x02 \x03(\x0b\x32\x18.Folder.FolderAccessData\x12\x30\n\x05\x65rror\x18\x03 \x01(\x0b\x32\x1c.folder.v3.FolderAccessErrorH\x00\x88\x01\x01\x42\x08\n\x06_error\"P\n\x11\x46olderAccessError\x12*\n\x06status\x18\x01 \x01(\x0e\x32\x1a.Folder.FolderModifyStatus\x12\x0f\n\x07message\x18\x02 \x01(\t2\x98\x01\n\rFolderService\x12\x86\x01\n\x0fGetFolderAccess\x12!.folder.v3.GetFolderAccessRequest\x1a\".folder.v3.GetFolderAccessResponse\",\x82\xd3\xe4\x93\x02&\"!/api/rest/vault/folders/v3/access:\x01*B*\n&com.keepersecurity.proto.api.folder.v3P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'folder_access_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n&com.keepersecurity.proto.api.folder.v3P\001'
  _globals['_FOLDERSERVICE'].methods_by_name['GetFolderAccess']._loaded_options = None
  _globals['_FOLDERSERVICE'].methods_by_name['GetFolderAccess']._serialized_options = b'\202\323\344\223\002&\"!/api/rest/vault/folders/v3/access:\001*'
  _globals['_GETFOLDERACCESSREQUEST']._serialized_start=79
  _globals['_GETFOLDERACCESSREQUEST']._serialized_end=242
  _globals['_GETFOLDERACCESSRESPONSE']._serialized_start=245
  _globals['_GETFOLDERACCESSRESPONSE']._serialized_end=434
  _globals['_CONTINUATIONTOKEN']._serialized_start=436
  _globals['_CONTINUATIONTOKEN']._serialized_end=477
  _globals['_GETFOLDERACCESSRESULT']._serialized_start=480
  _globals['_GETFOLDERACCESSRESULT']._serialized_end=627
  _globals['_FOLDERACCESSERROR']._serialized_start=629
  _globals['_FOLDERACCESSERROR']._serialized_end=709
  _globals['_FOLDERSERVICE']._serialized_start=712
  _globals['_FOLDERSERVICE']._serialized_end=864
# @@protoc_insertion_point(module_scope)
