# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tla.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder


_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ttla.proto\x12\ncommon.tla\"\x81\x01\n\rTLAProperties\x12\x12\n\nexpiration\x18\x01 \x01(\x03\x12@\n\x15timerNotificationType\x18\x02 \x01(\x0e\x32!.common.tla.TimerNotificationType\x12\x1a\n\x12rotateOnExpiration\x18\x03 \x01(\x08*\\\n\x15TimerNotificationType\x12\x14\n\x10NOTIFICATION_OFF\x10\x00\x12\x10\n\x0cNOTIFY_OWNER\x10\x01\x12\x1b\n\x17NOTIFY_PRIVILEGED_USERS\x10\x02\x42 \n\x1c\x63om.keepersecurity.proto.tlaP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tla_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\034com.keepersecurity.proto.tlaP\001'
  _globals['_TIMERNOTIFICATIONTYPE']._serialized_start=157
  _globals['_TIMERNOTIFICATIONTYPE']._serialized_end=249
  _globals['_TLAPROPERTIES']._serialized_start=26
  _globals['_TLAPROPERTIES']._serialized_end=155
# @@protoc_insertion_point(module_scope)
