# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: trashcan_sync.proto
# Protobuf Python Version: 5.29.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    5,
    '',
    'trashcan_sync.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import record_pb2 as record__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13trashcan_sync.proto\x12\x05Vault\x1a\x0crecord.proto\x1a\x1cgoogle/api/annotations.proto\"J\n\x19TrashcanContinuationToken\x12\x12\n\nsync_point\x18\x01 \x01(\x03\x12\x19\n\x11syncedToSyncOrder\x18\x02 \x01(\x03\"W\n\x13TrashcanSyncRequest\x12\x12\n\nsync_point\x18\x01 \x01(\x03\x12\x11\n\tmax_count\x18\x02 \x01(\x05\x12\x19\n\x11\x63ontinuationToken\x18\x03 \x01(\x0c\"\x87\x01\n\x14TrashcanSyncResponse\x12.\n\rtrashcan_data\x18\x01 \x01(\x0b\x32\x17.Vault.TrashcanSyncData\x12\x12\n\nsync_point\x18\x02 \x01(\x03\x12\x10\n\x08has_more\x18\x03 \x01(\x08\x12\x19\n\x11\x63ontinuationToken\x18\x04 \x01(\x0c\"\xe6\x01\n\x10TrashcanSyncData\x12/\n\x10trashcan_records\x18\x01 \x03(\x0b\x32\x15.Vault.TrashcanRecord\x12/\n\x10trashcan_folders\x18\x02 \x03(\x0b\x32\x15.Vault.TrashcanFolder\x12\x37\n\x18removed_trashcan_records\x18\x03 \x03(\x0b\x32\x15.Vault.TrashcanRecord\x12\x37\n\x18removed_trashcan_folders\x18\x04 \x03(\x0b\x32\x15.Vault.TrashcanFolder\"\x85\x01\n\x0eTrashcanRecord\x12\x12\n\nrecord_uid\x18\x01 \x01(\x0c\x12\x14\n\x0ctrashcan_uid\x18\x02 \x01(\x0c\x12\x33\n\x11\x66older_record_key\x18\x03 \x01(\x0b\x32\x18.Records.FolderRecordKey\x12\x14\n\x0c\x64\x61te_deleted\x18\x04 \x01(\x03\"\xa9\x01\n\x0eTrashcanFolder\x12\x12\n\nfolder_uid\x18\x01 \x01(\x0c\x12\x14\n\x0ctrashcan_uid\x18\x02 \x01(\x0c\x12\x12\n\nfolder_key\x18\x03 \x01(\x0c\x12/\n\x0f\x66older_key_type\x18\x04 \x01(\x0e\x32\x16.Records.RecordKeyType\x12\x14\n\x0c\x64\x61te_deleted\x18\x05 \x01(\x03\x12\x12\n\nparent_uid\x18\x06 \x01(\x0c\x32\x8d\x01\n\rRemoveService\x12|\n\x0cRemoveRecord\x12\x1a.Vault.TrashcanSyncRequest\x1a\x1b.Vault.TrashcanSyncResponse\"3\x82\xd3\xe4\x93\x02-\"(/api/rest/vault/folders/v3/trashcan/sync:\x01*B(\n\x18\x63om.keepersecurity.protoB\x0cTrashcanSyncb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'trashcan_sync_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030com.keepersecurity.protoB\014TrashcanSync'
  _globals['_REMOVESERVICE'].methods_by_name['RemoveRecord']._loaded_options = None
  _globals['_REMOVESERVICE'].methods_by_name['RemoveRecord']._serialized_options = b'\202\323\344\223\002-\"(/api/rest/vault/folders/v3/trashcan/sync:\001*'
  _globals['_TRASHCANCONTINUATIONTOKEN']._serialized_start=74
  _globals['_TRASHCANCONTINUATIONTOKEN']._serialized_end=148
  _globals['_TRASHCANSYNCREQUEST']._serialized_start=150
  _globals['_TRASHCANSYNCREQUEST']._serialized_end=237
  _globals['_TRASHCANSYNCRESPONSE']._serialized_start=240
  _globals['_TRASHCANSYNCRESPONSE']._serialized_end=375
  _globals['_TRASHCANSYNCDATA']._serialized_start=378
  _globals['_TRASHCANSYNCDATA']._serialized_end=608
  _globals['_TRASHCANRECORD']._serialized_start=611
  _globals['_TRASHCANRECORD']._serialized_end=744
  _globals['_TRASHCANFOLDER']._serialized_start=747
  _globals['_TRASHCANFOLDER']._serialized_end=916
  _globals['_REMOVESERVICE']._serialized_start=919
  _globals['_REMOVESERVICE']._serialized_end=1060
# @@protoc_insertion_point(module_scope)
